{% set data = load_setup_py_data() %}

package:
  name: "pymt_hydrotrend"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - hydrotrend 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hydrotrend 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_hydrotrend
  commands:
    - config_file=$(mmd-stage Hydrotrend . > MANIFEST && mmd-query Hydrotrend --var=run.config_file.path)
    - bmi-test pymt_hydrotrend.bmi:Hydrotrend --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the hydrotrend BMI.
  home: https://github.com/mcflugen/pymt_hydrotrend
  license: MIT License
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_hydrotrend
