[library]
[library.Hydrotrend]
language = "c"
library = "bmi_hydrotrend"
header = "hydrotrend/bmi_hydrotrend.h"
entry_point = "register_bmi_hydrotrend"

[build]
undef_macros = []
define_macros = []
libraries = []
library_dirs = []
include_dirs = []
extra_compile_args = []

[package]
name = "pymt_hydrotrend"
requirements = ["hydrotrend"]

[info]
package_author = "Eric Hutton"
package_author_email = "eric.hutton@colorado.edu"
github_username = "mcflugen"
package_license = "MIT"
summary = "PyMT plugin for hydrotrend"

